# Generated by Django 4.2.2 on 2023-10-14 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
